INSERT INTO users (name, email, rfc, role, area) VALUES
('CRUZ GARCIA LUIS ANGEL', 'ankhelo_gem@hotmail.com', 'CUGL870601LF2', 'worker', 'PV O&M TASTIOTA'),
('HERNANDEZ GUERRA EMILIO', 'emilio7692@hotmail.com', 'HEGE911224LRA', 'worker', 'PV O&M'),
('SANTOS GARCIA LUIS ERNESTO', 'santosgarcialuisernesto@gmail.com', 'SAGL9212288J8', 'worker', 'WIND O&M'),
('TOLEDO FUENTES ALBERTO', 'altf_68@outlook.com', 'TOFA680402H42', 'worker', 'WIND O&M'),
('CORTÉS PEÑA RAMSES', 'cortesramses672@gmail.com', 'COPR981221T16', 'worker', 'PV O&M'),
('LÓPEZ PÉREZ ALEXIS', 'lopa951013r78@revergygroup.com', 'LOPA951013R78', 'worker', 'PV O&M'),
('VELAZQUEZ BRAVO MIGUEL BALTAZAR', 'miguel.renov@outlook.com', 'VEBM960420HV7', 'worker', 'PV O&M TASTIOTA'),
('MANUEL GÓMEZ HENRY', 'manuel_momez@hotmail.com', 'MAGH970507JI5', 'worker', 'WIND O&M'),
('CRUZ CRUZ RICHARD', 'richardcruzcruz2000@gmail.com', 'CUCR000113RS6', 'worker', 'PV O&M TASTIOTA'),
('SANTIAGO SANTIAGO CRISTIAN ANAHI', 'anahisantiago802@gmail.com', 'SASC981011LZ0', 'worker', 'HSQE'),
('RODRIGUEZ HERRERA MICHEL ARMANDO', 'michellivanna29@gmail.com', 'ROHM950724F55', 'worker', 'PV O&M TASTIOTA'),
('BOCOBACHI CASTILLO SEBASTIAN', 'sbocobachis@gmail.com', 'BOCS9911129U0', 'worker','PV O&M TASTIOTA'),
('URBIETA MARTINEZ GUILLERMO', 'guillermourbieta4@gmail.com', 'UIMG9405079IA', 'worker', 'WIND O&M'),
('GARCIA SANCHEZ EZEQUIEL', 'gasejess@gmail.com', 'GASE9205064L9', 'worker', 'PV O&M'),
('CABRERA BENITEZ MARCOS', 'marcos_cb84@hotmail.com', 'CABM830504KG7', 'worker', 'WIND O&M'),
('GALLEGOS SANCHEZ ALAN JESUS', 'alangg689@gmail.com', 'GASJ010816EU8', 'worker', 'PV O&M TASTIOTA'),
('SÁNCHEZ MIGUEL SAMUEL', 'samuelsanchez062001@outlook.es', 'SAMS0103064U2', 'worker', 'PV O&M'),
('SALINAS TOLEDO ALFREDO', 'ing.alfedrosalinas@hotmail.com', 'SATA760626US6', 'worker', 'WIND O&M'),
('SANCHEZ JIMENEZ JOSUE', 'josssanchezsajj001024@gmail.com', 'SAJJ001024DQ1', 'worker', 'WIND O&M'),
('TOLEDO DÍAZ JUAN ANDRÉS', 'andrestdiaz9@gmail.com', 'TODJ970529538', 'worker', 'PV O&M'),
('SANCHEZ SOL OSCAR YAHIR', 'saso040617lu6@revergygroup.com', 'SASO040617LU6', 'worker', 'PV O&M TASTIOTA'),
('VILLA BRITO JOSE LUIS', 'jlvilla09@hotmail.com', 'VIBL780402DZA', 'worker', 'HSQE'),
('DUBLAN ANTONIO KEVIN', 'dublanantonio13@gmail.com', 'DUAK9206135FA', 'worker', 'PV O&M'),
('LOPEZ AVILA JOSE LUIS', 'lopeavila@hotmail.com', 'LOAL941025DFA', 'worker', 'HSQE'),
('JIMENEZ ESCOBAR REY DAVID', 'dav_es98@hotmail.com', 'JIER830808226', 'worker', 'WIND O&M'),
('VILLALOBOS REVUELTA CARLOS', 'oficial.carlos.villalobos@gmail.com', 'VIRC960223BT4', 'worker', 'WIND O&M'),
('PEREZ VALDIVIESO VICTOR MANUEL', 'vic-7771@hotmail.com', 'PEVV921018FX9', 'worker', 'PV O&M'),
('OROZCO MONTERO FERNANDO ', 'fernandorozco20_95@outlook.com', 'OOMF950420SF9', 'worker', 'PV O&M'),
('PERALTA MANUEL FELIPE DE JESÚS', 'peraltafelipe013@gmail.com', 'PEMF0102052N0', 'worker', 'PV O&M'),
('TOLEDO RASGADO KEVIN ', 'kevintoledort@gmail.com', 'TORK971027UW1', 'worker', 'PV O&M'),
('MATUS MATUS ALAN JESÚS', 'alanmatus@hotmail.com', 'MAMA981105EN9', 'worker', 'WIND O&M'),
('LOPEZ GALLEGOS REY DAVID', 'reylopezgallegos@gmail.com', 'LOGR011212440', 'worker', 'WIND O&M'),
('LOPEZ PINEDA JONATHAN', 'jonalope47@gmail.com', 'LOPJ021031BM9', 'worker', 'WIND O&M'),
('RIVERA GUTIERREZ KAREN NAYELI ', 'na.yeli_25rg@hotmail.com', 'RIGK000725U52', 'worker', 'WIND O&M'),
('MARCOS LOPEZ ELIEZER', 'eliezermarcoslopez@gmail.com', 'MALE830327U95', 'worker', 'WIND O&M'),
('PINEDA TRUJILLO ANGEL', 'angelpineda_92@hotmail.com', 'PITA920409DD4', 'worker', 'WIND O&M'),
('TOLEDO CUETO ROBERTO', 'roberto_cueto92@hotmail.com', 'TOCR921015IF5', 'worker', 'WIND O&M'),
('VILLALOBOS CALDERON ROBELSI', 'robelsinho@hotmail.com', 'VICR910808ARA', 'worker', 'WIND O&M'),
('ROJAS AMPARAN BONIFACIO', 'roab720519e45@revergygroup.com', 'ROAB720519E45', 'worker', 'PV O&M'),
('PEREZ MARTINEZ DAYAN', 'dayanperezmartinez1707@gmail.com', 'PEMD990717226', 'worker', 'WIND O&M'),
('MARTINEZ HERNANDEZ JOSE DE JESUS', 'josejesusmtz0109@gmail.com', 'MAHJ850109B17', 'worker', 'WIND O&M'),
('LOPEZ PINEDA ALAN', 'alan_lopez1986@hotmail.com', 'LOPA861119IA3', 'worker', 'WIND O&M'),
('LOPEZ MARTNEZ ROBERTO', 'roberto.lpmtz@gmail.com', 'LOMR900719UM1', 'worker', 'WIND O&M'),
('MARTINEZ GUTIERREZ VICTOR HUGO', 'victorhhdjdlox@gmail.com', 'MAGV000911QY6', 'worker', 'WIND O&M'),
('JIMENEZ PEREZ LUIS ENRIQUE', 'luisnahima02@gmail.com', 'JIPL940525H99', 'worker', 'WIND O&M'),
('LOPEZ CHENTE GUTIERREZ XHUNAXHI GUADALUPE', 'xhunaxhi15@gmail.com', 'LOGX9405133D3', 'worker', 'WIND O&M'),
('VASQUEZ SOLANO RAFAEL', 'solano_0823@hotmail.com', 'VASR890823BB4', 'worker', 'WIND O&M'),
('SAYNES MARTINEZ ALEJANDRO', 'sayneso9martz@gmail.com', ''),
('TOLEDO JIMENEZ ARMANDO', 'armandoJimenez168@hotmail.com', 'TOJA920904HP7', 'worker', 'WIND O&M'),
('MENDOZA CAZARES JUAN DIEGO GUADALUPE', 'mecj851212c87@revergygroup.com', 'MECJ851212C87', 'worker', 'WIND O&M'),
('ALONSO REGALADO JUAN CARLOS', 'alonsojuancarlos69@gmail.com', 'AORJ990401J51', 'worker', 'WIND O&M'),
('SANCHEZ PEREZ CARLOS ALBERTO', 'carloz_sp90@hotmail.com', 'SAPC901115RT0', 'worker', 'WIND O&M'),
('OROZCO ALTAMIRANO ELVIS JESUS', 'elvisj95@hotmail.com', 'OOAE9505227Q3', 'worker', 'WIND O&M'),
('SANCHEZ LOPEZ ALAN', 'alanlopez.0208@gmail.com', 'SALA010208MV2', 'worker', 'WIND O&M'),
('MENDEZ AQUINO JOSE ANTONIO', 'joseanto31@hotmail.com', 'MEAA990831IW8', 'worker', 'WIND O&M'),
('FLORES SANTIAGO EDWIN ANTONIO', 'mechanictec8310@gmail.com', 'FOSE8609052G2', 'worker', 'WIND O&M'),
('ANTONIO JIMENEZ PEDRO', 'antonio120jp@gmail.com', 'AOJP8505292G8', 'worker', 'WIND O&M'),
('TOLEDO ALVAREZ JONATHAN', 'jhonytoledo100@gmail.com', 'TOAJ930807E59', 'worker', 'WIND O&M'),
('TRUJILLO CHEVEZ FABIAN', 'fabian.trujil45@gmail.com', 'TUCF970818MG0', 'worker', 'WIND O&M'),
('LOPEZ MORALES ALUXALI', ''),
('GALLEGOS QUECHA JULIAN', 'gallegos_jq@hotmail.com', 'GAQJ9203295E4', 'manager WIND O&M', 'WIND O&M'),
('CONTRERAS HERNANDEZ JORGE ALBERTO', 'conher2504@gmail.com', 'COHJ830425SU1', 'manager PV O&M', 'PV O&M'),
('PINEDA MATUS EDGAR', 'ematus_69@hotmail.com', 'PIME690213EG1', 'manager PV O&M', 'PV O&M'),
('VILLALBA ENRIQUEZ SOFIA', 'villalba1422@hotmail.com', 'VIES9210214TA', 'manager HSQE', 'HSQE'),
('ESTEVA PINEDA RICARDO', 'riarte34@hotmail.com', 'EEPR840329BV7', 'manager RRHH', 'RRHH'),
('CANSECO ORDAZ JOSE IVAN ', 'canceco2@gmail.com', 'CAOI930227CC0', 'manager ALMACEN Y COMPRAS', 'ALMACEN Y COMPRAS'),
('PEÑA SOTO JOSE DE JESUS', 'j.pena.s@outlook.com', 'PESJ750125JWA', 'manager FINANCIERO', 'FINANCIERO'),
('CASTILLO VELASCO ERIC', 'ericcavelg@outlook.com', 'CAVE860814SJ7', 'manager OFICINA TECNICA', 'OFICINA TECNICA'), 